name: Lesson4

on: [push]
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
          board: [nrf7002dk/nrf5340/cpuapp, nrf7002dk/nrf5340/cpuapp/ns, nrf54l15dk/nrf54l15/cpuapp, nrf54l15dk/nrf54l15/cpuapp/ns, nrf52dk_nrf52832, nrf52840dk_nrf52840, nrf5340dk_nrf5340_cpuapp, nrf5340dk_nrf5340_cpuapp_ns, nrf9151dk_nrf9151_ns, nrf9160dk_nrf9160, nrf9160dk_nrf9160_ns, nrf9161dk_nrf9161, nrf9161dk_nrf9161_ns, nrf52833dk_nrf52833, nrf52840dk_nrf52840 ]
          project: [l4/l4_e1_sol, l4/l4_e2_sol, l4/l4_e3_sol]

              
              
          
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: image pull
      run: docker pull nordicplayground/nrfconnect-sdk:v2.9-branch
    - name: build sample
      run: docker run  --rm -v ${PWD}:/workdir/project -w /workdir/project/v2.9.0-v2.7.0 nordicplayground/nrfconnect-sdk:v2.9-branch  west build ${{ matrix.project }} -b ${{ matrix.board }} --build-dir ${{ matrix.project }}/build
